[package]
name = "intcode"
version = "0.1.0"
authors = ["Kevin Retzke <retzkek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
cursive = "0.15.0"
