[package]
name = "intcode"
version = "0.1.0"
authors = ["Kevin Retzke <kretzke@fnal.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
